name: Build NV RTX
on:
  workflow_dispatch:
    inputs:
      onnxruntime-version:
        type: string
        description: "ONNX Runtime version (e.g. 1.22.0)"
        required: true
env:
  GCC_VERSION: '11'
  CMAKE_VERSION: '3.28'
  PYTHON_VERSION: '3.10'
  NODE_VERSION: '18'
  XCODE_VERSION: '14.3.1'
  MACOSX_DEPLOYMENT_TARGET: '13.4'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            args: "--nvrtx -N"
            static: true
            feature-set: nvrtx
            cuda-version: '12.8.1'
            runs-on: ubuntu-22.04
          - target: x86_64-pc-windows-msvc
            args: "--nvrtx"
            static: true
            feature-set: nvrtx
            cuda-version: '12.8.1'
            runs-on: windows-2022
    steps:
      - name: Install cross-compile tools
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt update && sudo apt install -y gcc make gcc-11-aarch64-linux-gnu g++-11-aarch64-linux-gnu binutils-aarch64-linux-gnu
      - name: Remove unnecessary software
        if: runner.os == 'Linux'
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@v6
      - uses: Jimver/cuda-toolkit@v0.2.23
        if: matrix.cuda-version && runner.os != 'macOS'
        with:
          cuda: ${{ matrix.cuda-version }}
          method: network
          use-github-cache: false
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run builder
        run:
          deno run -A src/build.ts -v ${{ inputs.onnxruntime-version }} ${{ matrix.static && '-s' || '' }} ${{ matrix.args }}
      - uses: actions/upload-artifact@v4
        with:
          name: ortrs_${{ matrix.static && 'static' || 'dylib' }}${{ matrix.feature-set != 'none' && format('_{0}', matrix.feature-set) || '' }}-v${{ inputs.onnxruntime-version }}-${{ matrix.target }}
          path: artifact
          if-no-files-found: error
